[build]
  command = "npm run full-build"
  publish = "_site"

[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.js]
  minify = false
[build.processing.html]
  pretty_urls = true     # eleventy should handle
[build.processing.images]
  compress = true  